theme: jekyll-theme-merlot

# Mighty-Jump

![Mighty Jump Cover Art](platformercoverart.PNG)

## How to play the game

Using the XBox Controller to Move in my game:
- Left stick: run/walk
- A button: jump
- Start button: pause
- P keyboard key: unpause
- S turns on/off sounds
- M turns on/off music


Enemies:
- Blue blinking monsters


Awards/ Things to earn:
- Earn a heart once a level is completed
- Coins increase your score by 5
- First aid kits give you lives
- Band-aids give you hearts 


Obstacles:
- 4 levels
- If time runs out, you lose a life 
- After you get 20 seconds on the first part of each level, and the time runs out and you die, you only have 10 seconds to complete it ater that. 
- DONT FALL THROUGH THE HOLES IN THE GROUND OR YOU WILL DIE!!


The Goal:
- To have fun, and complete all the levels

Level 1:

![Mighty Jump Game Play Level 1](capture1.PNG)

Level 2:

![Mighty Jump Game Play Level 2](capture2.PNG)

## Coming Soon!

1. New Levels
2. Different Worlds
3. 2 player
